import * as React from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Loader2, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select } from '@/components/ui/select'
import { Checkbox } from '@/components/ui/checkbox'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
  tripBatchSchema,
  tripBatchFormDefault,
  BATCH_STATUSES,
  BATCH_STATUS_LABELS,
} from '@/schemas/tripBatch'

function FieldError({ message }) {
  if (!message) return null
  return <p className="mt-1 text-xs text-destructive">{message}</p>
}

function FormSection({ title, children }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  )
}

function Field({ label, error, children, hint }) {
  return (
    <div>
      <Label>{label}</Label>
      <div className="mt-1.5">{children}</div>
      {hint && !error && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}
      <FieldError message={error} />
    </div>
  )
}

// Shared create/edit form for trip batches. `batchCode` is generated by the
// server and shown read-only in edit mode.
export function TripBatchForm({
  initialValues,
  trips,
  batchCode,
  isSubmitting,
  submitLabel,
  onSubmit,
}) {
  const defaults = React.useMemo(() => {
    const base = initialValues || tripBatchFormDefault
    return {
      ...base,
      bookingOpenDate: base.bookingOpenDate || '',
      bookingCloseDate: base.bookingCloseDate || '',
    }
  }, [initialValues])

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    mode: 'onChange',
    resolver: zodResolver(tripBatchSchema),
    defaultValues: defaults,
  })

  const values = watch()
  const totalSeats = Number(values.totalSeats) || 0
  const bookedSeats = Number(values.bookedSeats) || 0
  const availableSeats = Math.max(0, totalSeats - bookedSeats)

  return (
    <form onSubmit={handleSubmit(onSubmit)} noValidate className="space-y-6">
      <FormSection title="Trip">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Trip" error={errors.tripId?.message}>
            <Select {...register('tripId')} defaultValue="">
              <option value="">Select a trip</option>
              {trips.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}
                  {t.destination?.name ? ` — ${t.destination.name}` : ''}
                  {` (${t.tripCode})`}
                </option>
              ))}
            </Select>
          </Field>
          {batchCode && (
            <Field label="Batch code" hint="Generated server-side and not editable.">
              <Input value={batchCode} readOnly disabled />
            </Field>
          )}
        </div>
      </FormSection>

      <FormSection title="Dates">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Departure date" error={errors.departureDate?.message}>
            <Input type="date" aria-invalid={!!errors.departureDate} {...register('departureDate')} />
          </Field>
          <Field label="Return date" error={errors.returnDate?.message}>
            <Input type="date" aria-invalid={!!errors.returnDate} {...register('returnDate')} />
          </Field>
          <Field
            label="Booking open"
            error={errors.bookingOpenDate?.message}
            hint="Optional booking window start."
          >
            <Input type="date" {...register('bookingOpenDate')} />
          </Field>
          <Field
            label="Booking close"
            error={errors.bookingCloseDate?.message}
            hint="Must be on/after the booking open date."
          >
            <Input type="date" {...register('bookingCloseDate')} />
          </Field>
        </div>
      </FormSection>

      <FormSection title="Pricing">
        <div className="grid gap-4 sm:grid-cols-3">
          <Field label="Price per person" error={errors.price?.message}>
            <Input type="number" min={0} placeholder="51999" {...register('price')} />
          </Field>
          <Field
            label="Original price"
            error={errors.originalPrice?.message}
            hint="Shown struck-through when greater than the price."
          >
            <Input type="number" min={0} placeholder="56999" {...register('originalPrice')} />
          </Field>
          <Field label="Currency" error={errors.currency?.message}>
            <Input placeholder="INR" {...register('currency')} />
          </Field>
        </div>
      </FormSection>

      <FormSection title="Capacity">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Total seats" error={errors.totalSeats?.message}>
            <Input type="number" min={1} placeholder="16" {...register('totalSeats')} />
          </Field>
          <Field label="Booked seats" error={errors.bookedSeats?.message}>
            <Input type="number" min={0} {...register('bookedSeats')} />
          </Field>
        </div>
        <div className="mt-4 flex items-center gap-3 rounded-lg border border-border bg-muted/30 p-3 text-sm">
          <Users className="h-4 w-4 shrink-0 text-primary" />
          <span>
            Total <strong>{Math.max(0, totalSeats)}</strong>
            <span className="mx-2 text-muted-foreground">·</span>
            Booked <strong>{bookedSeats}</strong>
            <span className="mx-2 text-muted-foreground">·</span>
            Available{' '}
            <strong className={availableSeats === 0 ? 'text-destructive' : 'text-primary'}>
              {availableSeats}
            </strong>
          </span>
        </div>
      </FormSection>

      <FormSection title="Status & publishing">
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Status" error={errors.status?.message}>
            <Select {...register('status')}>
              {BATCH_STATUSES.map((s) => (
                <option key={s} value={s}>
                  {BATCH_STATUS_LABELS[s]}
                </option>
              ))}
            </Select>
          </Field>
          <div className="flex items-end pb-1">
            <label className="flex items-center gap-2.5 text-sm">
              <Checkbox
                checked={values.published}
                onCheckedChange={(v) => setValue('published', v, { shouldValidate: true })}
              />
              <span>
                Published
                <span className="ml-1 text-xs text-muted-foreground">(visible on the public site)</span>
              </span>
            </label>
          </div>
        </div>
      </FormSection>

      <FormSection title="Notes">
        <Field label="Internal notes" error={errors.notes?.message} hint="Not shown publicly.">
          <Textarea rows={3} placeholder="e.g. Departure aligned with a festival weekend" {...register('notes')} />
        </Field>
      </FormSection>

      <div className="flex justify-end gap-3">
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? <Loader2 className="animate-spin" /> : null}
          {isSubmitting ? 'Saving…' : submitLabel}
        </Button>
      </div>
    </form>
  )
}
